### ISSUE TITLE
Leading Slashes Should be Stripped When Linting Naming

### ISSUE THREAD

**Issue by abgier-avraha** [Place1/openapi-linter#1]
Take for example this:
`path "/camelCasePathname/" must follow the CamelCase naming convention`

The route name is clearly written in camel case and the swagger spec is valid. The slashes should just be ignored when analysing case or am I missing something?

**Comment by Place1** [comment]
yep, that's a bug. fixed in 9917e150e77719be74ebf88e0c877c5630026297

**Comment by abgier-avraha** [comment]
👍
